# Generated by Django 4.1.2 on 2022-10-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.TextField()),
                ('phone', models.IntegerField()),
                ('WorkAddress', models.TextField()),
                ('reqGender', models.TextField()),
                ('reqQualification', models.TextField()),
                ('reqVacancy', models.TextField()),
            ],
        ),
    ]
